[package]
name = "credible"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
arboard = "3.4.1"
crossterm = "0.28.1"
derive_setters = "0.1.6"
indexmap = "2.7.0"
ratatui = "0.29.0"
rusqlite = "0.32.1"
